oauth.jwt.signing-key: secretsecretsecretsecretsecretsecret

security.ldap:
  url: 'ldaps://foo.com'
  domain: 'foo.com'
  pattern: '(&(objectClass=user)(userPrincipalName={0})(memberof=CN=foo,OU=foo,OU=foo,OU=foo,DC=bar,DC=com))'

server:
  port: 8080

spring.cloud.consul.enabled: false

