pricing:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: '{cipher}ce1b12d0a01c6af23e1b9df7e525ff4acd49f24895508de19f2154dfd446c101b766942b87fa36328dc554fe8d980b99'
    url: 'jdbc:sqlserver://sqlserver;databaseName=pricing_service'
    username: pricing
  # needs to be set even for non-UA Var pricing
  united:
    url: 'http://nowhere.to.go'
    sourceId: dummy
  ehf:
    realtime:
      merchants:

flyway:
  user: 'pricing_flyway'
  password: '{cipher}3821c486c4f42d49aae0b7a9efbb9bf8add35aa94caf99670ce6726cf97c27619d1b31133a1d7273581680113bbcfb6a'
  url: 'jdbc:sqlserver://sqlserver:1433;databaseName=pricing_service'

b2s.flyway.migrationStrategy: MIGRATE

spring.cloud.consul.enabled: false

