pricing:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: '{cipher}ee420a68bcd1befe427db394520a2be8c5c398e1bacd10ecb13e24a5cae31964'
    url: 'jdbc:sqlserver://sqlserver;databaseName=pricing_service'
    username: pricing
  # needs to be set even for non-UA Var pricing
  united:
    url: 'http://nowhere.to.go'
    sourceId: dummy
  ehf:
    realtime:
      merchants:

flyway:
  user: 'pricing_flyway'
  password: '{cipher}e928cb593bbf3a2c8b66a4deafc2100f58a1b4b9aa853e13ed8cce4134f6fdd2'
  url: 'jdbc:sqlserver://sqlserver:1433;databaseName=pricing_service'

b2s.flyway.migrationStrategy: MIGRATE

spring.cloud.consul.enabled: false

